/**
 * Enum defining standardized step names for logging within the Inngest handler and its logic.
 * Using an enum improves type safety and reduces typos compared to raw strings.
 */
export enum HandlerStepName {
  // --- Handler Entry/Exit/Validation ---
  HANDLER_ENTERED = "HANDLER_ENTERED",
  HANDLER_COMPLETED = "HANDLER_COMPLETED",
  HANDLER_ERROR = "HANDLER_ERROR",
  HANDLER_EARLY_EXIT = "HANDLER_EARLY_EXIT",
  HANDLER_INVALID_DATA = "HANDLER_INVALID_DATA",
  HANDLER_MISSING_EVENT_ID = "HANDLER_MISSING_EVENT_ID",
  STEP_UNDEFINED = "STEP_UNDEFINED",

  // --- Sandbox Management ---
  SANDBOX_CHECK_START = "SANDBOX_CHECK_START",
  SANDBOX_CHECK_END = "SANDBOX_CHECK_END",
  GET_SANDBOX_ID_START = "GET_SANDBOX_ID_START",
  GET_SANDBOX_ID_END = "GET_SANDBOX_ID_END",
  GET_SANDBOX_ID_SKIP = "GET_SANDBOX_ID_SKIP",
  CREATE_SANDBOX_STEP_START = "CREATE_SANDBOX_STEP_START",
  CREATE_SANDBOX_STEP_END = "CREATE_SANDBOX_STEP_END",

  // --- State Management ---
  HANDLER_STATE_RECEIVED = "HANDLER_STATE_RECEIVED", // Logged in index.ts initially
  HANDLER_STATE_BEFORE_SANDBOX = "HANDLER_STATE_BEFORE_SANDBOX", // Logged in index.ts initially
  STATE_INIT_START = "STATE_INIT_START",
  STATE_INIT_END = "STATE_INIT_END",
  STATE_INITIALIZED = "STATE_INITIALIZED",
  STATE_REUSED = "STATE_REUSED",
  STATE_STATUS_MISSING = "STATE_STATUS_MISSING",
  STATE_BEFORE_KV_SET = "STATE_BEFORE_KV_SET",
  STATE_RESTORE_NETWORK = "STATE_RESTORE_NETWORK",
  HANDLER_STATE_FROM_KV_RESULT = "HANDLER_STATE_FROM_KV_RESULT",
  HANDLER_FINAL_STATE_MISSING = "HANDLER_FINAL_STATE_MISSING",
  HANDLER_CRITICAL_STATE_LOSS_NO_RESULT = "HANDLER_CRITICAL_STATE_LOSS_NO_RESULT",
  HANDLER_CRITICAL_STATE_LOSS_NO_FINAL = "HANDLER_CRITICAL_STATE_LOSS_NO_FINAL",
  FINAL_STATE_LOGGING = "FINAL_STATE_LOGGING",

  // --- Dependencies (Tools/Agents) ---
  CREATE_TOOLS_START = "CREATE_TOOLS_START",
  CREATE_TOOLS_END = "CREATE_TOOLS_END",
  CREATE_AGENTS_START = "CREATE_AGENTS_START",
  CREATE_AGENTS_END = "CREATE_AGENTS_END",
  AGENT_DEPS_CREATED = "AGENT_DEPS_CREATED",

  // --- Network Execution ---
  NETWORK_RUN_START = "NETWORK_RUN_START",
  NETWORK_RUN_SUCCESS = "NETWORK_RUN_SUCCESS",
  NETWORK_RUN_ERROR = "NETWORK_RUN_ERROR",
  NETWORK_RUN_NO_RESULT = "NETWORK_RUN_NO_RESULT",

  // --- Result Processing / Command Execution ---
  HANDLER_PROCESS_RESULT = "HANDLER_PROCESS_RESULT",
  HANDLER_RUN_COMMAND = "HANDLER_RUN_COMMAND",
  HANDLER_COMMAND_EXECUTED = "HANDLER_COMMAND_EXECUTED",
  HANDLER_NO_COMMAND = "HANDLER_NO_COMMAND",
  HANDLER_REINVOKE_AFTER_COMMAND = "HANDLER_REINVOKE_AFTER_COMMAND",
  HANDLER_HUMAN_INPUT_NEEDED = "HANDLER_HUMAN_INPUT_NEEDED",
  HANDLER_NO_ACTION = "HANDLER_NO_ACTION",
  E2B_STUBBED = "E2B_STUBBED", // Specific to stubbed command execution
}
